### ISSUE TITLE
port mapping 

### ISSUE THREAD

**Issue by burtsevyg** [docker/docs#10279]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)
https://docs.docker.com/compose/compose-file/#ports

Docs say that:

`Note: Port mapping is incompatible with network_mode: host`

and than follow example:
```
ports:
  - target: 80
    published: 8080
    protocol: tcp
    mode: host
```

In my project:
short syntax

```
  service:
    image: myimage
    ports:
      - 10000:8801
    networks:
      - default
```

does not work, but long syntax work as expected:

```
  service:
    image: myimage
    ports:
      - target: 8801
        published: 10000
        protocol: tcp
        mode: host
    networks:
      - default
```

For start service I use:
docker stack deploy --prune --with-registry-auth=true -c docker-compose.yml myservice

I don understand why this is happening.
