### ISSUE TITLE
Why does the ImageName in customized log driver tag include the digest?

### ISSUE THREAD

**Issue by yuchen9459** [docker/docs#10506]
I set the log driver of the running docker containers as Fluentd, and using fluent-bit as a pipeline to collect and send logs to ElasticSearch and show logs in Kibana afterwards. The tag was changed into `ImageName` in my case, but I found all the tags include the long digest of the docker image instead of the version, which is quite verbose and useless for the monitoring task. Can anybody tell what might be the reason for this? And how to simply use only the docker image name as a tag?

My `docker-compose.yml` is :

version: "3.3"

```
services:
  watcher:
    image: dataplatform.docker.com/test_image:0.0.2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    command: [ "pipenv", "run", "python", "./watcher/watcher.py" ]
    logging:
      driver: fluentd
      options:
        tag: "{{.ImageName}}"
    networks:
      - elastic
```
My `Fluent-bit.conf` config file:

```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    debug
    Parsers_File ./parsers.conf

[INPUT]
    Name Forward
    Port 24224

[FILTER]
    Name     parser
    Match    *
    Parser   json
    Key_Name log
    Reserve_Data true

[OUTPUT]
    Name  es
    Match *
    Host  elasticsearch
    Port  9200
    Index fluent_bit
    Type  docker
    Include_Tag_Key true
    Tag_Key Docker_Image_Name
```

The output of the tag name:

`dataplatform.docker.com/test_image:0.0.2@sha256:8a7bd3f4f525f227a6e027b221f2138da421553c697fb099a7ba4f4755a6c7c2`
