### ISSUE TITLE
max_replicas_per_node needs to be under placement

### ISSUE THREAD

**Issue by chrisbecke** [docker/docs#10652]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

e.g. 
```
version: "3.8"
services:
  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - frontend
      - backend
    deploy:
      mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 1
```
