### ISSUE TITLE
Missing documentation on how named volumes works in docker

### ISSUE THREAD

**Issue by rawatnaresh** [docker/docs#11193]
### Problem description

I have a very simple node js app and the project structure looks like this.

`index.js`

`package.json`

`package-lock.json`

`Dockerfile`
```
FROM node:12.18.2-alpine
WORKDIR /test-app
COPY package.json package-lock.json ./
RUN npm i
COPY . ./
EXPOSE 3000
ENTRYPOINT [ "node", "index.js" ]
```
`docker-compose.yml`
```
version: '3.2'

services:
  test-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/test-app
      - "test_app_node_modules:/test-app/node_modules"
volumes:
  test_app_node_modules:
    driver: local
```
When I hit the `docker-compose up` it'll first build the image and start the containers. As you can see I'm doing `npm i`  which will install `node_modules`  during the build phase.
and while starting the container, the docker will [bind mount](https://docs.docker.com/storage/bind-mounts/) the current directory on the host machine to the `test-app` directory on the container. this overrides everything in the container including `node_modules`

and the next step is named volumes and according to the [documentation here](https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container): 
> If you start a container which creates a new volume, as above, and the container has files or directories in the directory to be mounted (such as /app/ above), the directory’s contents are copied into the volume. The container then mounts and uses the volume, and other containers which use the volume also have access to the pre-populated content.

 which means I created an empty volume and mounted it to the container and should cause missing dependency error but my app is running properly.

**This suggests empty volumes will inherit files from the image they are mounted in but not the container** but I couldn't find anywhere in the documentation.

### Problem location

- URL: https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container
