### ISSUE TITLE
docker-compose files usage when using docker remotely

### ISSUE THREAD

**Issue by ArwynFr** [docker/docs#11216]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The documentation does not explain how docker behaves when using docker-compose files with a remote server.

For instance, secrets files are looked on the client :
```yml
version: "3.7"
secrets:
  my-secret:
    file: /var/run/my-secret
services:
  my-service:
    # ...
    secrets:
      - my-secret
```
```
user@client$ export DOCKER_HOST=tcp://server:2376
user@client$ docker stack deploy --compose-file docker-compose.yml my-stack
```
The `/var/run/my-secret` file is looked for on the `client` machine rather than the `server` swarm node

The behavior is probably similar with configs, but how about bind mounting volumes, etc ... ?
