### ISSUE TITLE
Profiles example doesn't seem to work

### ISSUE THREAD

**Issue by keeganwitt** [docker/docs#12392]
File: [compose/profiles.md](https://docs.docker.com/compose/profiles/) shows `profiles` being used with file version `3.9`, but this doesn't actually work.  Here I modified the Wordpress [example](https://docs.docker.com/compose/wordpress/) to use `profiles`.

```yaml
version: '3.9'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
#     profiles:
#       - wp
     profiles: ['wp']
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
```
```
$ docker-compose up -d
ERROR: The Compose file '.\docker-compose.yml' is invalid because:
Unsupported config option for services.wordpress: 'profiles'
```
I'm guessing this only works with certain versions of Compose file, but the docs don't say which. I also tried with `2.4`. Or maybe this feature got removed?

I'm using the latest stable Docker Desktop for Windows
```
$  docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```
