### ISSUE TITLE
Add port, SG change and Route53 Alias to the HTTPS ALB example/documentation

### ISSUE THREAD

**Issue by jasonumiker** [docker/docs#12744]
File: [cloud/ecs-integration.md](https://docs.docker.com/cloud/ecs-integration/)

You show adding a certificate and flipping the listener to HTTPS but not how to change the port to 443 (leaving it as the strange https://www.domain.com:80).

Here is an example that also updates the port, fixed the security group to allow the new 443 port through and sets a Route53 Alias record to point to the ALB to line up with the actual name you want so the certificate works.

```
version: "3.9"
services:
  webapp:
    build: .
    image: 1234567891234.dkr.ecr.ap-southeast-2.amazonaws.com/container:latest
    ports:
      - "80:80"

x-aws-cloudformation:
  Resources:
    WebappTCP80Listener:
      Properties:
        Certificates:
          - CertificateArn: "arn:aws:acm:ap-southeast-2:1234567891234:certificate/4acc2716-8555-49ec-adec-8f565c135eee"
        Protocol: HTTPS
        Port: 443
    Default80Ingress:
      Properties:
        CidrIp: "0.0.0.0/0"
        IpProtocol: "tcp"
        FromPort: 443
        ToPort: 443
    LoadBalancerAlias:
      Type: AWS::Route53::RecordSet
      Properties:
        AliasTarget:
          DNSName: 
            Fn::GetAtt:
              - LoadBalancer
              - DNSName
          HostedZoneId: 
            Fn::GetAtt:
              - LoadBalancer
              - CanonicalHostedZoneID
        HostedZoneId: ZABCDEFGHIJKL
        Name: www.domain.com
        Type: A  
```
