### ISSUE TITLE
Sub-options for depends_on are not explained in the reference. 

### ISSUE THREAD

**Issue by itsfarseen** [docker/docs#13073]
File: [compose/compose-file/compose-file-v3.md](https://docs.docker.com/compose/compose-file/compose-file-v3/)

```
depends_on:
  db:
    condition:  what are all the possible values for this?
    what other options are available? 
```
