### ISSUE TITLE
Tutorial on ECS deployment not up-to-date anymore

### ISSUE THREAD

**Issue by alexander-esser** [docker/docs#13469]
### Problem description

The tutorial on AWS ECS deployments using Docker Compose does not seem to be up-to-date anymore.
Parts of it, regarding the health checks, are practically not working anymore.

### Problem location

**Links**:
- https://docs.docker.com/cloud/ecs-integration/
- https://github.com/docker/docker.github.io/edit/master/cloud/ecs-integration.md

### Project description

According to the official Docker tutorial and documentation (https://docs.docker.com/cloud/ecs-integration/), one could specify a health check by

```
x-aws-cloudformation:
  Resources:
    WebappTCP80TargetGroup:
      Properties:
        HealthCheckPath: /health
        Matcher:
          HttpCode: 200-499
```

However, AWS does not allow specifying the above properties of an health checks for TCP target groups.		  
The above example leads to an error `Health check paths are not supported for TCP health checks`.

One could, of course, change the TCP target group to an HTTP target group.
Then, however, the protocol of the target group would not be compatible to the protocol of the corresponding Listener anymore.
