### ISSUE TITLE
Wrong data for preferences in container/service deploy

### ISSUE THREAD

**Issue by thejoelinux** [docker/docs#15351]
File: [compose/compose-file/deploy.md](https://docs.docker.com/compose/compose-file/deploy/)

I've tried to put this:

```
    deploy:
      placement:
        preferences:
          - datacenter=us-east
```

in my docker-compose.yml file, it doesn't work and raise the error : **services.my-service.deploy.placement.preferences.0 must be a mapping**

After some research, it turns out this is not the way preferences work.
