### ISSUE TITLE
Variable substituation in environment files does not match documentatoin

### ISSUE THREAD

**Issue by osresearch** [docker/docs#16110]
File: [compose/env-file.md](https://docs.docker.com/compose/env-file/)

> Compose supports parameter expansion in environment files. Parameter expansion is applied for unquoted and double-quoted values. Both braced (${VAR}) and unbraced ($VAR) expressions are supported.

The unbraced expansion doesn't seem to work and the braced expansion doesn't pickup values from the `environment:` section.

`docker-compose.yaml`:
```
version: '3'
services:
  test:
    image: alpine
    command: env
    env_file:
      - env.file
    environment:
      FOO: bar
```

`env.file`:
```
BAD=$FOO
BAR=${FOO}
```

and the resulting config does not expand `$FOO` as well as doesn't substitute the value of `${FOO}` from the environment:
```
% docker-compose config
services:
  test:
    command: env
    environment:
      BAD: $$FOO
      BAR: ''
      FOO: bar
      image: alpine
version: '3'
% docker-compose --version
docker-compose version 1.29.2, build unknown
```
