### ISSUE TITLE
ECS SSL Documentation is incorrect and misleading

### ISSUE THREAD

**Issue by hwnprsd** [docker/docs#16541]
File: [cloud/ecs-integration.md](https://docs.docker.com/cloud/ecs-integration/#setting-ssl-termination-by-load-balancer)

The documentation to have SSL Termination inside the AWS LoadBalancer is incorrect. Infact, it's misleading to the point where the docker-compose breaks if the docs is taken as a reference.

**Comment by hwnprsd** [comment]
https://techsparx.com/software-development/docker/docker-ecs/load-balancer/https.html

This is a better alternative for people who want to achieve the same

**Comment by hwnprsd** [comment]
This is my docker-compose.yml
Anyone who is not familiar with cloud formation properties, but wants to achieve SSL using docker-compose ECS and ACM here is my docker-compose

```
version: "3.8"

services:
  mailer:
    container_name: "flaq-mailer"
    image:  ECR_IMAGE_1
    build:
      context: ./mailer
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
    restart: always
    networks:
      - flaq_net

  api:
    container_name: "flaq-api"
    image: ECR_IMAGE_2
    build:
      context: ./api
    environment:
      AMQP_SERVER_URL: ${AMQP_SERVER_URL}
    restart: always
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
    ports:
      - 80:80
    networks:
      - flaq_net

networks:
  flaq_net:
    driver: bridge

x-aws-cloudformation:
  Resources:
    WebappTCP443Listener:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      Properties:
        LoadBalancerArn:
          Ref: LoadBalancer
        DefaultActions:
          - ForwardConfig:
              TargetGroups:
                - TargetGroupArn:
                    Ref: ApiTCP80TargetGroup
            Type: forward
        Certificates:
          - CertificateArn: "YOUR CERTIFICATE ARN"
        Protocol: TLS
        Port: 443
```

If you now add a CNAME record with the DNS of your load balancer, `https://YOUR_DOMAIN.XXX` should work.
