### ISSUE TITLE
How to specify IP in ports "Long syntax"?

### ISSUE THREAD

**Issue by bluepuma77** [docker/docs#16651]
When I want to listen to a dedicated IP address, how can I specify that in ports "Long syntax":
```
ports:
  - target: 80
    published: 8080
    protocol: tcp
    mode: host
```
https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

File: [compose/compose-file/compose-file-v3.md](https://docs.docker.com/compose/compose-file/compose-file-v3/)
