### ISSUE TITLE
How to get content into secret file

### ISSUE THREAD

**Issue by dazza-codes** [docker/docs#16999]
File: [build/ci/github-actions/secrets.md](https://docs.docker.com/build/ci/github-actions/secrets/)

How is content populated in a secret file to be used with `secret-files`?  For example, how can we put multiple values for an env into a secret file when some of the values come from github secrets?

Suppose a `Dockerfile` loads environment variables from a secret file, e.g.

```
RUN --mount=type=cache,target=/root/.cache \
    --mount=type=secret,id=app_build_env \
    if [ -f /run/secrets/app_build_env ]; then export $(cat /run/secrets/app_build_env | xargs); fi \
    && python3 -m pip install -r requirements.txt
```

One of the items in `app_build_env` comes from github secrets, e.g.
```
GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
```

That entry needs to be in an env-file (which is also in docker-compose `secrets` file settings).  The docker build then assumes that `GITHUB_TOKEN` is an environment variable for a python pip installation.  The `requirements.txt` file contains libraries installed via git URLs from a private github repository and the URL uses `GITHUB_TOKEN` for auth-n-auth of that private pip package.

The current examples of secrets demonstrate how to get a `github_token` value into a build secret, where the secret would be named `github_token`.  That is:

```
        name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: user/app:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
```

What if the same secret must be put or merged into a secret file instead - how is that done with a build step?
