### ISSUE TITLE
`build` and `image` in docker compose files

### ISSUE THREAD

**Issue by miparnisari** [docker/docs#17732]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

My `docker-compose.yaml` file has something like this:

```yaml
name: openfga
services:

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    command: run
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=postgres://postgres:password@postgres:5432/postgres?sslmode=disable
      - OPENFGA_DATASTORE_MAX_OPEN_CONNS=100 #see postgres container
      - OPENFGA_TRACE_ENABLED=true
      - OPENFGA_TRACE_SAMPLE_RATIO=0.3
      - OPENFGA_TRACE_OTLP_ENDPOINT=otel-collector:4317
      - OPENFGA_METRICS_ENABLED=true
      - OPENFGA_METRICS_ENABLE_RPC_HISTOGRAMS=true
      - OPENFGA_PLAYGROUND_ENABLED=true
    networks:
      - default
    ports:
      - "8080:8080" #http
      - "8081:8081" #grpc
      - "3000:3000" #playground
      - "2112:2112" #prometheus metrics
    healthcheck:
      test: ["CMD", "/usr/local/bin/grpc_health_probe", "-addr=openfga:8081"]
      interval: 5s
      timeout: 30s
      retries: 3
```

Meanwhile, `docker-compose.override.yaml` has this:

```yaml
name: openfga-dev
services:
  openfga:
    build:
      context: ..
    environment:
      - OPENFGA_TRACE_SAMPLE_RATIO=1
      - OPENFGA_PROFILER_ENABLED=true
    ports:
      - "3002:3001" #profiler (port 3001 is exposed for Grafana)
      
```

When I run `docker-compose --verbose up`, I see that a service named `openfga-dev` is launched and `openfga` has `OPENFGA_TRACE_SAMPLE_RATIO=1` (so it is reading the override file). However, it is still using the `openfga/openfga:latest` image instead of building from scratch.

### Location

https://docs.docker.com/compose/extends/
