### ISSUE TITLE
Reading Swarm managed secrets into a container environment variable doesn't work

### ISSUE THREAD

**Issue by securitypedant** [docker/docs#17774]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The page titled "How to use secrets in Docker Compose" states...

- The secrets attribute under each service defines the secrets you want to inject into the specific container.
- The top-level secrets section defines the variables db_password and db_root_password and provides the file that populates their values.
- The deployment of each container means Docker creates a temporary filesystem mount under /run/secrets/<secret_name> with their specific values.

Which works. However, in the advanced compose file example it shows...

```
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password
```

Which implies that MYSQL_PASSWORD_FILE environment variable declaration would read the contents of the file  /run/secrets/db_password and result with an environment variable MYSQL_PASSWORD containing the contents of the file. However, after much testing, I cannot get the _FILE feature to work. Instead the environment variable MYSQL_PASSWORD_FILE contains the string "/run/secrets/db_root_password"

Either this is a bug and it should work, or the documentation is wrong or outdated.

### Location

https://docs.docker.com/compose/use-secrets/

### Suggestion

Either update the documentation to reflect how the feature works, or maybe this should result in a bug in Docker itself to implement the desired functionality.
