### ISSUE TITLE
Which version of docker is required

### ISSUE THREAD

**Issue by averater** [docker/docs#18304]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I'm having issues starting devcontainers when following the guide on how to start contributing. I wanted to know which versions of vscore/docker/etc is need3ed.

### Location

https://docs.docker.com/get-docker/

### Suggestion

Add version requirements

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue. Maybe related to this change https://github.com/docker/docs/pull/18286

A couple of ways to fix this.
- Wait for Docker Desktop 4.24 to be released tomorrow and update to that version.
- In the compose file, change `develop` to `x-develop`.
```
services:
  server:
    build:
      context: .
      target: dev
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
    x-develop:
      watch:
        - action: sync
          path: .
          target: /src
          ignore:
            - node_modules/
```
