### ISSUE TITLE
validate-upstream GitHub Action replacement is incorrect for forks

### ISSUE THREAD

**Issue by TBBle** [docker/docs#18431]
### Is this a docs issue?

- [ ] My issue is about the documentation content or website

### Type of issue

Other

### Description

When calling the validate-upstream action from a fork of a project, e.g., https://github.com/TBBle/buildkit/actions/workflows/docs-upstream.yml, [the generated `HUGO_MODULE_REPLACEMENTS` value](https://github.com/TBBle/buildkit/actions/runs/6497247439/job/17645917380#step:6:178) is incorrect:

```
... --set *.args.HUGO_MODULE_REPLACEMENTS="github.com/TBBle/buildkit -> github.com/TBBle/buildkit refs/heads/oci_images_should_not_have_empty_layers" ...
```

Of course, that first parameter `github.com/TBBle/buildkit` won't match [the import in hugo.yaml](https://github.com/docker/docs/blob/580ec0e746e2e697e9ef7c5c2b54e8bb3647b33b/hugo.yaml#L248-L257).

### Location

https://github.com/TBBle/buildkit/actions/runs/6497247439/job/17645917380#step:6:178

### Suggestion

The first parameter should be fork-parent of the repo in such cases, but I'm not sure if GHA can reliably extract that, or even if we would want to rely on that relationship.

So the best case solution is probably to make this a parameter the caller can pass in and hard-code, since, e.g., in [the BuildKit caller](https://github.com/moby/buildkit/blob/19d7b7109da6852d88d5d77e3f4657c93db169c8/.github/workflows/docs-upstream.yml), it already knows which module its replacing because it's taken a copy of the list of relevant paths.

i.e. the buildkit workflow could look like this, which requires a new input for the validate-upstream workflow, e.g., `module-name`

```
name: docs-upstream

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
    paths:
      - '.github/workflows/docs-upstream.yml'
      - 'docs/buildkitd.toml.md'
      - 'docs/attestations/slsa-definitions.md'
      - 'docs/attestations/attestation-storage.md'
      - 'frontend/dockerfile/docs/reference.md'
  pull_request:
    paths:
      - '.github/workflows/docs-upstream.yml'
      - 'docs/buildkitd.toml.md'
      - 'docs/attestations/slsa-definitions.md'
      - 'docs/attestations/attestation-storage.md'
      - 'frontend/dockerfile/docs/reference.md'

jobs:
  validate:
    uses: docker/docs/.github/workflows/validate-upstream.yml@main
    with:
      module-name: https://github.com/moby/buildkit
```

The previously-existing repo parameter isn't right, as the one caller I checked points that at the fork, not the head. This problem actually existed in that pre-hugo situation too, as the repo input was used to select the right `fetch-remote` entry, and similarly to this issue, would fail to match the right entry when running in a fork.

I also note that [currently BuildKit and buildx have disabled their callers of this workflow](https://github.com/moby/buildkit/pull/4334#discussion_r1359078324), so my running it in the first place was an accident of "disabled workflows do not stay disabled in forks". I've not yet located the discussion referenced there as to why it was disabled.

This also means I haven't checked if a PR does the right thing; I suspect it'd have the right-hand side incorrect, as it lacks anything like [the pre-hugo PR handling](https://github.com/docker/docs/blob/d5312d53e255a24e421dfe6c3344359e10271cb8/.github/workflows/validate-upstream.yml#L49-L54).
