### ISSUE TITLE
Sample compose.yaml requires separate password.txt file, but lists password without protection right above that

### ISSUE THREAD

**Issue by vbalalian** [docker/docs#18569]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

```yaml
services:
  server:
    build:
      context: .
    ports:
      - 5000:5000
    environment:
      - POSTGRES_PASSWORD=**mysecretpassword**
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/**db-password**
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  **db-password:
    file: db/password.txt**
```

### Location

https://docs.docker.com/language/python/develop/

### Suggestion

I tried using the password.txt variable in the other section, but I'm a noob and only ran into errors
