### ISSUE TITLE
Error: ENOENT: no such file or directory, open '/run/secrets/db-password'

### ISSUE THREAD

**Issue by OpenTechConsult** [docker/docs#18651]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

I have undertaken to follow this tutorial. Right from the start I got this error when running the docker compose --build command as described in the tutorial. I don't understand what I did incorrectly.
All I did was add the /db directory to the root of the project and the password.txt file in the /db directory.

Here are some details about my environment

Operating system: Linux Mint 21.2 Cinnamon

Docker version:
     Client: Docker Engine - Community
     Version: 24.0.7
     Context: desktop-linux

Here is the content of the Dockerfile 

```Dockerfile
# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/engine/reference/builder/

ARG NODE_VERSION=18.18.2

FROM node:${NODE_VERSION}-alpine

# Use production node environment by default.
ENV NODE_ENV production


WORKDIR /usr/src/app

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage a bind mounts to package.json and package-lock.json to avoid having to copy them into
# into this layer.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

# Run the application as a non-root user.
USER node

# Copy the rest of the source files into the image.
COPY . .

# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD node src/index.js
```

Here is the content of the docker compose.yaml file 

```yaml
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: example
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
```

Here is the error I get

```
docker-nodejs-sample-db-1      | 
docker-nodejs-sample-db-1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
docker-nodejs-sample-db-1      | 
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.857 UTC [1] LOG:  starting PostgreSQL 16.0 (Debian 16.0-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.857 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.857 UTC [1] LOG:  listening on IPv6 address "::", port 5432
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.859 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.864 UTC [16] LOG:  database system was shut down at 2023-11-13 08:35:29 UTC
docker-nodejs-sample-db-1      | 2023-11-13 08:37:09.868 UTC [1] LOG:  database system is ready to accept connections
docker-nodejs-sample-server-1  | Error: ENOENT: no such file or directory, open '/run/secrets/db-password'
docker-nodejs-sample-server-1  |     at Object.openSync (node:fs:603:3)
docker-nodejs-sample-server-1  |     at Object.readFileSync (node:fs:471:35)
docker-nodejs-sample-server-1  |     at Object.init (/usr/src/app/src/persistence/postgres.js:21:41)
docker-nodejs-sample-server-1  |     at Object.<anonymous> (/usr/src/app/src/index.js:17:4)
docker-nodejs-sample-server-1  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
docker-nodejs-sample-server-1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
docker-nodejs-sample-server-1  |     at Module.load (node:internal/modules/cjs/loader:1119:32)
docker-nodejs-sample-server-1  |     at Module._load (node:internal/modules/cjs/loader:960:12)
docker-nodejs-sample-server-1  |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:86:12)
docker-nodejs-sample-server-1  |     at node:internal/main/run_main_module:23:47 {
docker-nodejs-sample-server-1  |   errno: -2,
docker-nodejs-sample-server-1  |   syscall: 'open',
docker-nodejs-sample-server-1  |   code: 'ENOENT',
docker-nodejs-sample-server-1  |   path: '/run/secrets/db-password'
docker-nodejs-sample-server-1  | }
docker-nodejs-sample-server-1 exited with code 1

```

If anyone could give me some help. I'm new to using docker and docker compose.

### Location

https://docs.docker.com/language/nodejs/containerize/
