### ISSUE TITLE
Wrong prometheus config

### ISSUE THREAD

**Issue by djdejawu** [docker/docs#18774]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

It's a configuration error in example file [here](https://docs.docker.com/config/daemon/prometheus/#prerequisites)
Yours (WRONG)
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name:
      "docker"
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9323"]
 ```
 
My (WORKS)
 ```
   # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name:
      "docker"
      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.

    static_configs:
      - targets: ["host.docker.internal:9323"]
```

### Location

https://docs.docker.com/config/daemon/prometheus/#configure-and-run-prometheus

### Suggestion

Fix it
