### ISSUE TITLE
How to manage manifest annotation in distributed build across multiple runners

### ISSUE THREAD

**Issue by neilime** [docker/docs#18835]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

I can't find what I'm looking for

### Description

I'm trying to set annotation while create multi-platform manifest, but it misses some howto documentation:

```sh
docker buildx imagetools create --annotation "org.opencontainers.image.description=Test" context --annotation "org.opencontainers.image.revision=3a1cea69f0cddd44812bb66c7f2c0223cb9ab57c" --annotation "org.opencontainers.image.source=https://github.com/hoverkraft-tech/ci-github-container" --annotation "org.opencontainers.image.title=ci-github-container" --annotation "org.opencontainers.image.url=https://github.com/hoverkraft-tech/ci-github-container" --annotation "org.opencontainers.image.version=pr-214" --tag ghcr.io/hoverkraft-tech/ci-github-container/application-2:pr-214 ghcr.io/hoverkraft-tech/ci-github-container/application-1@sha256:b60112eb363180ec1f065aa8d8cb66f6df179e60146574eb96f6d6e47633aa05 ghcr.io/hoverkraft-tech/ci-github-container/application-1@sha256:4e1ecd8d251f02e382f6f5d7824afda08619aba364f75b194ea614fa44761469
```

But when I inspect the manifest there are no annotations

```sh
docker buildx imagetools inspect ghcr.io/hoverkraft-tech/ci-github-container/application-1:pr-214  --format "{{json .Manifest}}"
```

I've try to use prefixed annotation with "manifest:" like `--annotation "manifest:org.opencontainers.image.description=Test"`

But it does not work.

### Location

https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by dvdksn** [comment]
Hi @neilime thanks for reaching out. I'm working on the docs for annotations right at this moment! Aiming to have them ready early next week. For the `imagetools create` command specifically, I did run into some strange issues with that one. See https://github.com/docker/buildx/issues/2148

However I think your `imagetools inspect` command would be trying to get the annotations on the **image index**. By default, they're are attached at the image manifest level.

What if you try to either:

- Use the `index:` prefix to attach the annotations to the image index, e.g. `index:org.opencontainers.image.description=Test` (or both: `index,manifest:org.opencontainers.image.description=Test`)
- Use `imagetools inspect` on the manifest directly, like this:

  ```console
  $ docker buildx imagetools inspect ghcr.io/hoverkraft-tech/ci-github-container/application-1:pr-214@sha256:b60112eb363180ec1f065aa8d8cb66f6df179e60146574eb96f6d6e47633aa05 --raw
  ```

  (note the `--raw` here, I think there's something fishy with the `--format "{{json}}"` for the inspect command regarding manifests currently.)

**Comment by neilime** [comment]
Hi I got a clue:

- Use latest version of buildx.
```yml
- uses: docker/setup-buildx-action@v3
        with:
          version: latest
```
- Define annotation levels (`manifest,manifest-descriptor` for platform specific build, `index` for merge manifest):
```yml
      - uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,manifest-descriptor  # Important for digest annotation (used by Github packages)

    # OR 
      - uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index  # Important for manifest annotation (used by Github packages)
```

## Final workflow

```yml
name: ci

on:
  push:
    branches:
      - "main"

env:
  REGISTRY_IMAGE: user/app

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,manifest-descriptor # Important for digest annotation (used by Github packages)

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest # Important to have annotation feature

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest # Important to have annotation feature

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index # Important for manifest annotation (used by Github packages)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \ 
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(jq -cr '.annotations | map("--annotation \"" + . + "\"") | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \ # Annotate manifest
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
```
