### ISSUE TITLE
[docker compose] depends_on has no correct indentation

### ISSUE THREAD

**Issue by blueprismo** [docker/docs#19458]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I tried to have a quick test with `docker-compose up -d --scale queue=1` and I see the following error message:
```sh
ERROR: The Compose file './compose.yml' is invalid because:
services.queue.depends_on contains unsupported option: 'restart'
```

In my simple compose.yml file, I am using the long syntax in the depends_on block, actually copy-pasted from the official documentation:
```yaml
version: "3.9"
services:
  queue:
    image: nginx:1.25.3
    depends_on:
      web:
        condition: service_healthy
        restart: true         ##### <----- This is what is complaining about!
  web:
    image: test_image
    entrypoint: /entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "touch /tmp/a"]
      interval: 5s
      timeout: 60s
      retries: 10
```

My docker versions are:
```
# docker version 
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:17 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

## docker compose version
Docker Compose version v2.24.5

## system
"Ubuntu 20.04.6 LTS (Focal Fossa)"
```

### Location

https://docs.docker.com/compose/compose-file/05-services/#long-syntax-1

### Suggestion

It would be nice that the documentation is addressed accordingly, because right now we can see:
```yaml
services:
  web:
    build: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
```
In the documentation. In my local computer with docker desktop works, but not in my ubuntu server.
