### ISSUE TITLE
Unclear `extends` usage note

### ISSUE THREAD

**Issue by leocencetti** [docker/docs#19494]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Other

### Description

The `important` block in the [extends](https://docs.docker.com/compose/multiple-compose-files/extends/) documentation page is unclear. In particular, it is unclear what the _"base Compose file"_ refers to. 

> When you use multiple Compose files, you must make sure all paths in the files are relative to the base Compose file. This is required because extend files need not be valid Compose files. Extend files can contain small fragments of configuration. Tracking which fragment of a service is relative to which path is difficult and confusing, so to keep paths easier to understand, all paths must be defined relative to the base file.

Consider the following directory structure:
```
project/
├── compose.yaml
└── module1/
         ├── compose.module1.yaml 
         └── compose.extendable.yaml
```
In this example, `compose.yaml` includes  `compose.module1.yaml`, and services in `compose.module1.yaml` extend services in  `compose.extendable.yaml`. How should services in `compose.module1.yaml` reference services in `compose.extendable.yaml`?

1) `compose.yaml` is the  _"base Compose file"_ (base file of the project):
    ```yaml
    # compose.module1.yaml
    services:
      service1:
        extends:
          file: module1/compose.extendable.yaml
          service: extendable1
    ```
    This is the behaviour in `compose < 2.24.2` (see [this issue](https://github.com/docker/compose/issues/11412))
2) `compose.module1.yaml` is the  _"base Compose file"_ (current compose file):
    ```yaml
    # compose.module1.yaml
    services:
      service1:
        extends:
          file: compose.extendable.yaml
          service: extendable1
    ```
    This is the behaviour in `compose >= 2.24.2`

Given the inconsistency in the behavior of compose across different versions, this documentation bit should be as clear as possible.

### Location

https://docs.docker.com/compose/multiple-compose-files/extends/
