### ISSUE TITLE
ImagePullBackOff error caused by current CI/CD config (Node.js - CI/CD)

### ISSUE THREAD

**Issue by berkesayin** [docker/docs#20008]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

The default CI/CD configuration builds and pushes the image to Dockerhub for `linux/amd64` (OS/ARCH) platform.
(Language specific guides, Node.js, Configure CI/CD section)

<img width="1227" alt="latest" src="https://github.com/docker/docs/assets/53861551/0e9e470e-1ce4-4280-b9cd-eac7cc9018eb">

My environment: 
- OS/Arch: MacOS, M1 Apple Silicon arm64
- Docker version: 26.0.0
- Docker Compose version: v2.26.1-desktop.1

With the current workflow, pushing the image only compatible with `linux/amd64` platform causes the errors, `ImagePullBackOff` or `ErrImagePull`, when I go on to the next section, `Test your Node.js deployment`. 

<img width="1475" alt="error" src="https://github.com/docker/docs/assets/53861551/b24030e0-9475-4dc5-a5bd-c24fc18d831f">

### Location

https://docs.docker.com/language/nodejs/configure-ci-cd/

### Suggestion

According to Docker docs, `building and pushing multi-platform image with GitHub Actions` would be the best practice for this guide. Reference: https://docs.docker.com/build/ci/github-actions/multi-platform/

Update `main.yaml` as multi platform image: 

```yaml
name: Build and push
uses: docker/build-push-action@v5
with:
  context: .
  platforms: linux/amd64,linux/arm64/v8 # Only this line added
  push: true
  target: prod
  tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
```

Now the image is compatible with `linux/arm64` as well as `linux/amd64`. And Kubernetes deployment at next step is successful.

PR: #20009
