### ISSUE TITLE
Git Actions configuration misspell

### ISSUE THREAD

**Issue by gomesrod** [docker/docs#20801]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

At the page Introduction to Github Actions (https://docs.docker.com/build/ci/github-actions/) we have the following:

```
STEP ONE
...
3. Create a new Repository variable named DOCKER_USERNAME and your Docker ID as value.
```

But later the Actions YAML files reference the variable by DOCKERHUB_USERNAME

```
-
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```

Running the steps as presented causes the Action to fail (variable DOCKERHUB_USERNAME does not exist)

### Location

https://docs.docker.com/build/ci/github-actions/

### Suggestion

It looks like one of the variable names is misspelled. The text authors can fix it by determining which one is the expected and use the same naming in all places.
