### ISSUE TITLE
The sample circleci pipeline , doesn't work with --attest type=provenance,mode=max

### ISSUE THREAD

**Issue by ozbillwang** [docker/docs#20983]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Doesn't work with `--attest type=provenance,mode=max`

### Description

Follow the [document](https://docs.docker.com/scout/integrations/ci/circle-ci/) to Integrate Docker Scout with Circle CI, I have successfully the build the image, but when follow the docker scout document (https://docs.docker.com/scout/policy/#no-outdated-base-images), I added the option `--attest type=provenance,mode=max` to `docker buildx build` command, it reports error

```
unknown flag: --attest
See 'docker buildx build --help'.
```

https://app.circleci.com/pipelines/github/alpine-docker/used-for-docker-scout-score-check-only/6/workflows/92cbda51-6ef8-4d56-89a5-a272817976a7/jobs/3

.circleci/config.yml for your reference

```
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      IMAGE_TAG: <docker/scout-demo-service:latest>. # fake image name 
    steps:
      # Checkout the repository files
      - checkout

      # Set up a separate Docker environment to run `docker` commands in
      - setup_remote_docker:
          version: 20.10.24

      # Install Docker Scout and login to Docker Hub
      - run:
          name: Install Docker Scout
          command: |
            env
            curl -sSfL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh -s -- -b /home/circleci/bin
            echo $DOCKER_HUB_PAT | docker login -u $DOCKER_HUB_USER --password-stdin

      # Build the Docker image
      - run:
          name: Build Docker image
          command: platform="linux/arm64,linux/amd64" && \
           docker buildx build --tag alpine/used-for-docker-scout-score-check-only:v3 \
              --platform "${platform}" \
              --push --attest type=provenance,mode=max .

      # Run Docker Scout
      - run:
          name: Scan image for CVEs
          command: |
            docker-scout cves $IMAGE_TAG --exit-code --only-severity critical,high

workflows:
  build-docker-image:
    jobs:
      - build
 ```

### Location

https://docs.docker.com/scout/integrations/ci/circle-ci/
