### ISSUE TITLE
Conflicting explanation about auto-starting profiles and dependencies

### ISSUE THREAD

**Issue by chbrandt** [docker/docs#20995]
### Is this a docs issue?

- [X] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

In section [how-tos / profiles / Auto-starting profiles and dependencies resolution](https://docs.docker.com/compose/how-tos/profiles/#auto-starting-profiles-and-dependency-resolution), I believe the first example of compose is missing a `profiles:  [tools]` argument under `db` service. For it says in the command-line example below (in the comment): `This runs db-migrations (and,if necessary, start db) by implicitly enabling the profiles 'tools'`.

The second example has it right (according to the example comment).

### Location

https://docs.docker.com/compose/how-tos/profiles/

### Suggestion

If that is the case -- *i.e.*, when explicitly starting a compose service from the command-line `depends_on` is not resolved but `profiles` is --, the first example compose should read:
```yaml
services:
  backend:
    image: backend

  db:
    image: mysql
    profiles: [tools]

  db-migrations:
    image: backend
    command: myapp migrate
    depends_on:
      - db
    profiles:
      - tools
```
for the command-line comment (without the parenthesis) to be satisfied:
```bash
# This runs db-migrations and,if necessary, start db
# by implicitly enabling the profiles `tools`
$ docker compose run db-migrations
```
