### ISSUE TITLE
GitHub Actions "Distribute build across multiple runners" leads to "ERROR: tag is needed when pushing to registry"

### ISSUE THREAD

**Issue by KonradHoeffner** [docker/docs#22014]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

There's a problem with the website

### Description

When I follow <https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners> I get the error
`Error: buildx failed with: ERROR: tag is needed when pushing to registry`.

The problem seems to be that the following part does not specify a tag:

```yaml
     - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,"name=${{ env.DOCKERHUB_REPO }},${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true
```

### Location

https://docs.docker.com/build/ci/github-actions/multi-platform/

### Suggestion

Please verify that the example works, ideally there should be a live example.

**Comment by sarahsanders-docker** [comment]
Hi @KonradHoeffner, thanks for flagging this! We certainly want to make sure our code samples are accurate. Explicitly adding `:latest` to the `name=` field should fix the error. 

Example: `outputs: type=image,"name=${{ env.DOCKERHUB_REPO }}:latest,${{ env.GHCR_REPO }}:latest",push-by-digest=true,name-canonical=true,push=true`

Note, this fix ensures that when pulling the image without specifying a tag, you get the most recently built version. If you require strict versioning you should use explicit version tags instead. 

Please let me know if you are still running into errors using the `:latest` tag! 😄 I will get the docs updated in the meantime.

**Comment by crazy-max** [comment]
> Explicitly adding `:latest` to the `name=` field should fix the error.

We don't need to set latest as we are pushing by digest with `push-by-digest=true` and merging manifests from them and create tags in `merge` job.

> When I follow https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners I get the error
> `Error: buildx failed with: ERROR: tag is needed when pushing to registry`.

Can you post a full repro (workflow yaml and logs) please? Best would be to have a link to your workflow run so we can take a look. Thanks

**Comment by KonradHoeffner** [comment]
@crazy-max: Sure! [The failing run](https://github.com/KonradHoeffner/rickview/actions/runs/13286580208) uses the following workflow:

```yaml
name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches: ['master']
    tags: '[0-9]+\.[0-9]+\.[0-9]+*'
    paths-ignore:
      - '.gitignore'
      - '.env.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/release.yml'
      - 'LICENSE'
      - 'README.md'
  pull_request:
  pull_request_target:
    branches: ['master']
    paths-ignore:
      - '.gitignore'
      - '.env.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/release.yml'
      - 'LICENSE'
      - 'README.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: konradhoeffner/rickview

jobs:
  build:
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
#        config:
#          - {arch: 'arm64'}
#          - {arch: 'amd64'}
#    runs-on: ${{ matrix.config.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          #tags: |
          #  ${{ steps.meta.outputs.tags }}
          #  ghcr.io/konradhoeffner/rickview:latest-${{matrix.config.arch}}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          #outputs: type=image,"name=${{ env.DOCKERHUB_REPO }},${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true
          outputs: type=image,"name=${{ env.GHCR_REPO }}",push-by-digest=true,name-canonical=true,push=true
          #cache-from: type=registry,ref=ghcr.io/konradhoeffner/rickview:master-${{matrix.config.arch}}
          #cache-to: type=inline

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          #images: ${{ env.GHCR_REPO }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        #  docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
        #    $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.GHCR_REPO }}@sha256:%s ' *)
      - name: Inspect image
        #  docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ steps.meta.outputs.version }}
        run: |
          docker buildx imagetools inspect ${{ env.GHCR_REPO }}:${{ steps.meta.outputs.version }}
```
