### ISSUE TITLE
Instructions for collecting Docker metrics using Prometheus from docs is not reproducible

### ISSUE THREAD

**Issue by QazCetelic** [docker/docs#22367]
### Is this a docs issue?

- [x] My issue is about the documentation content or website

### Type of issue

Information is incorrect

### Description

I have the same issue as #6028, however the suggested solution did not work for me.

I have used `127.0.0.1` in my docker config as recommended.
`/etc/docker/daemon.json`:
```yml
{
  "metrics-addr": "127.0.0.1:9323",
  "default-address-pools": [
    {
      "base" : "172.16.0.0/12",
      "size" : 24
    }
  ]
}
```

And I'm using `host.docker.internal` in my Prometheus config as suggested in the docs.
```yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]
```

However, I'm unable to reach the port from within the Prometheus container even though I can reach it outside using `curl http://127.0.0.1:9323/metrics`.

### Location

https://docs.docker.com/engine/daemon/prometheus/

### Suggestion

Update the tutorial page in the documentation
