### ISSUE TITLE
Document max attempts for restart

### ISSUE THREAD

**Issue by masterada** [docker/docs#7414]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/#restart)

The following will restart the container in case of failure a maximum of 10 times, with exponential interval between restart attempts:
`restart: on-failure:10`

This feature is not documented.

**Comment by dalees** [comment]
Note: this is implemented in `parse_restart_spec` function: https://github.com/docker/compose/blob/master/compose/config/types.py#L85

It appears to function as described above.

**Comment by glours** [comment]
You should define the [`restart_policy` of the `deploy` attribute](https://github.com/compose-spec/compose-spec/blob/master/deploy.md#restart_policy) to achieve this:
```
deploy:
  restart_policy:
    condition: on-failure
    delay: 5s
    max_attempts: 3
    window: 120s
```
