### ISSUE TITLE
No documentation on compose/swarm template syntax

### ISSUE THREAD

**Issue by jamesdh** [docker/docs#8478]
### Problem description

There does not appear to be any mention in the docs of the templating syntax available for use in Docker Swarm's compose files. I originally stumbled upon it from @t3476's answer on rexray/rexray#804. Today I was setting up a service with named volumes that could be scaled and vaguely remembered that solution. I spent a solid hour looking around for documentation and couldn't find anything. I then started digging for that old GitHub issue and eventually found it while also stumbling across @thaJeztah's suggestion in moby/moby#30770 to create an issue here, and hence...here we are. 

An extremely simple example of what I'm referring to:

```
elastic_replica:
  image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-beta1
  deploy:
    replicas: 3
  volumes:
    - elastic_replica:/usr/share/elasticsearch/data

volumes:
  elastic_replica: {
    name: '{{.Service.Name}}-{{.Task.Slot}}'  
  }
```

Again, as in the two examples I linked above as well as several other forum posts around the internet that give examples similar to the above, I can't find anything in the docs that refers to this. 

### Problem location

- I couldn't find the information I wanted. I expected to find it near the following URL: https://docs.docker.com/storage/volumes/

### Suggestions for a fix

In my opinion there should probably be a section dedicated just to templating. Examples, use cases, what vars are available, etc. Note, that this is distinctly different than https://docs.docker.com/compose/compose-file/#variable-substitution
