### ISSUE TITLE
docker-compose does not pass through args from the environment

### ISSUE THREAD

**Issue by sersorrel** [docker/docs#9047]
File: [compose/compose-file/index.md](https://docs.docker.com/compose/compose-file/)

The docs state:

>You can omit the value when specifying a build argument, in which case its value at build time is the value in the environment where Compose is running.
>
>```yaml
>args:
>  - buildno
>  - gitcommithash
>```

so it's my understanding that the following docker-compose.yaml:

```yaml
version: '3'

services:
  myservice:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - FOO
```

should pass through the environment variable `FOO` from docker-compose's environment to the Dockerfile, but it doesn't:

```console
$ FOO=bar docker-compose config
services:
  myservice:
    build:
      args:
        FOO: ''
      context: /home/ubuntu
      dockerfile: Dockerfile
version: '3.0'
```

therefore either the docs or docker-compose are buggy.
