### ISSUE TITLE
docker compose docs for using network none don't work

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docs#9129]
I presume this is actually a bug in one of the many docker/moby/somewhere repos...

I tried to make a compose file for a swarm stack where the service had no network, and it fails...

the docs:
```
services:
  web:
    ...
    networks:
      nonet: {}

networks:
  nonet:
    external: true
    name: none
```

what i did:

```
version: "3.6"

services:
  test:
    image: alpine
    command: ls -al /test
    networks:
      nonet:
    volumes:
      - test:/test
    deploy:
      replicas: 1
      restart_policy:
        condition: none

volumes:
  test:
    driver: swarm
    driver_opts:
      # user: nobody
      uid: 65534
      guid: 65534

networks:
  nonet:
    external: true
    name: none
```

what docker 19.03 gave me:

```
sven@yoga260:~/src/github/seaweedfs/docker-plugin-seaweedfs$ docker network ls
NETWORK ID          NAME                 DRIVER              SCOPE
1ff656c456b8        bridge               bridge              local
31ce077afab6        docker_gwbridge      bridge              local
8a3a8508fd8c        host                 host                local
hia5omtuwmzp        ingress              overlay             swarm
c8264d62426d        none                 null                local
sven@yoga260:~/src/github/seaweedfs/docker-plugin-seaweedfs$ docker stack deploy -c test.yml test
Creating service test_test
failed to create service test_test: Error response from daemon: could not find the corresponding predefined swarm network: network none not found
sven@yoga260:~/src/github/seaweedfs/docker-plugin-seaweedfs$ 

```
