### ISSUE TITLE
Document usage of mapping host:port in swarm mode

### ISSUE THREAD

**Issue by joy4eg** [docker/docs#9155]
Here is the original [issue](https://github.com/moby/moby/issues/32299).

### TL;DR
Using of host:port is not supported in swarm mode:
Here is the compose example:
```yaml
version: '3.4'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8001:8001"
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
```
Docker output:
```
WARN[0000] ignoring IP-address (127.0.0.1:8001:8001/tcp) service will listen on '0.0.0.0'
```

I guess it should be document somewhere like [here](https://docs.docker.com/compose/compose-file/)
