### ISSUE TITLE
A network of type overlay shouldn't have an IPAM declaration.

### ISSUE THREAD

**Issue by ay0o** [docker/docs#9883]
### Problem description

If a network declaration has both `driver: overlay` and `ipam` variables, the network will fail to be created. That's expected, given that `overlay` should not use `ipam` because it's built-in as mentioned here https://www.docker.com/blog/understanding-docker-networking-drivers-use-cases/

So far it has been working, but starting on `19.03.5` (yesterday's release), the network no longer works (the driver is empty).

For example, the following worked till `19.03.4`, even if it doesn't make sense to have the `ipam` section given that `overlay` manages everything,
```
networks:
  default:
    name: foo
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
```

However, in `19.03.5` it no longer works, creating a network with an empty (not `null`) driver.

### Problem location

Missing in the docs.

### Project version(s) affected

19.03.5+

### Suggestions for a fix

Where would be the best file to add such information?
